// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrryvktosmjcshxmfelj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhycnl2a3Rvc21qY3NoeG1mZWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTQwMDIsImV4cCI6MjA2OTQ3MDAwMn0.rQnwzYihc4MX561VdKigVAZhDeOTtLW9ZxvAbf-0ffY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});